//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIRWin10BLE {
    
    
    #region Component Designer generated code 
    public partial class IBleInterface_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::RMIRWin10BLE.@__IBleInterface.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::RMIRWin10BLE.IBleInterface), typeof(global::RMIRWin10BLE.IBleInterface_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::RMIRWin10BLE.IBleInterface), typeof(global::RMIRWin10BLE.IBleInterface_))]
    internal sealed partial class @__IBleInterface : global::java.lang.Object, global::RMIRWin10BLE.IBleInterface {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_ConnectBLE0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_DisconnectBLE1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_DiscoverUEI2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_ConnectUEI3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_DisconnectUEI4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_DiscoverServices5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetFeatures6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetSubscription7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetStage8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_SetDisconnecting9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_IsDisconnecting10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_IsScanning11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_IsConnected12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_HasCCCD13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_NeedsCCCD14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetListSize15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetListItem16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetItemName17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetRssi18;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetInCount19;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetInDataSize20;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetInData21;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_ReadSignalStrength22;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_WritePacket23;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetSentState24;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_SetSentState25;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_UpdateConnection26;
        
        private @__IBleInterface(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::RMIRWin10BLE.@__IBleInterface.staticClass = @__class;
            global::RMIRWin10BLE.@__IBleInterface.j4n_ConnectBLE0 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "ConnectBLE", "(Ljava/lang/String;)Ljava/lang/String;");
            global::RMIRWin10BLE.@__IBleInterface.j4n_DisconnectBLE1 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "DisconnectBLE", "()V");
            global::RMIRWin10BLE.@__IBleInterface.j4n_DiscoverUEI2 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "DiscoverUEI", "(Z)V");
            global::RMIRWin10BLE.@__IBleInterface.j4n_ConnectUEI3 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "ConnectUEI", "(Ljava/lang/String;)Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_DisconnectUEI4 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "DisconnectUEI", "()Ljava/lang/String;");
            global::RMIRWin10BLE.@__IBleInterface.j4n_DiscoverServices5 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "DiscoverServices", "()Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetFeatures6 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetFeatures", "()Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetSubscription7 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetSubscription", "()Ljava/lang/String;");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetStage8 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetStage", "()I");
            global::RMIRWin10BLE.@__IBleInterface.j4n_SetDisconnecting9 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "SetDisconnecting", "(Z)V");
            global::RMIRWin10BLE.@__IBleInterface.j4n_IsDisconnecting10 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "IsDisconnecting", "()Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_IsScanning11 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "IsScanning", "()Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_IsConnected12 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "IsConnected", "()Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_HasCCCD13 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "HasCCCD", "()Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_NeedsCCCD14 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "NeedsCCCD", "()Z");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetListSize15 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetListSize", "()I");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetListItem16 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetListItem", "(I)Ljava/lang/String;");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetItemName17 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetItemName", "(I)Ljava/lang/String;");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetRssi18 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetRssi", "(I)I");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetInCount19 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetInCount", "()I");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetInDataSize20 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetInDataSize", "()I");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetInData21 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetInData", "(I)[B");
            global::RMIRWin10BLE.@__IBleInterface.j4n_ReadSignalStrength22 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "ReadSignalStrength", "()I");
            global::RMIRWin10BLE.@__IBleInterface.j4n_WritePacket23 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "WritePacket", "([B)V");
            global::RMIRWin10BLE.@__IBleInterface.j4n_GetSentState24 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "GetSentState", "()I");
            global::RMIRWin10BLE.@__IBleInterface.j4n_SetSentState25 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "SetSentState", "(I)V");
            global::RMIRWin10BLE.@__IBleInterface.j4n_UpdateConnection26 = @__env.GetMethodID(global::RMIRWin10BLE.@__IBleInterface.staticClass, "UpdateConnection", "(IIII)V");
        }
        
        public string ConnectBLE(string portName) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::RMIRWin10BLE.@__IBleInterface.j4n_ConnectBLE0, global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, portName)));
            }
        }
        
        public void DisconnectBLE() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_DisconnectBLE1);
            }
        }
        
        public void DiscoverUEI(bool start) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_DiscoverUEI2, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(start));
            }
        }
        
        public bool ConnectUEI(string address) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_ConnectUEI3, global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, address))));
            }
        }
        
        public string DisconnectUEI() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::RMIRWin10BLE.@__IBleInterface.j4n_DisconnectUEI4));
            }
        }
        
        public bool DiscoverServices() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_DiscoverServices5)));
            }
        }
        
        public bool GetFeatures() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetFeatures6)));
            }
        }
        
        public string GetSubscription() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetSubscription7));
            }
        }
        
        public int GetStage() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetStage8)));
            }
        }
        
        public void SetDisconnecting(bool disconnecting) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_SetDisconnecting9, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(disconnecting));
            }
        }
        
        public bool IsDisconnecting() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_IsDisconnecting10)));
            }
        }
        
        public bool IsScanning() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_IsScanning11)));
            }
        }
        
        public bool IsConnected() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_IsConnected12)));
            }
        }
        
        public bool HasCCCD() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_HasCCCD13)));
            }
        }
        
        public bool NeedsCCCD() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_NeedsCCCD14)));
            }
        }
        
        public int GetListSize() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetListSize15)));
            }
        }
        
        public string GetListItem(int ndx) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetListItem16, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(ndx)));
            }
        }
        
        public string GetItemName(int ndx) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetItemName17, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(ndx)));
            }
        }
        
        public int GetRssi(int ndx) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetRssi18, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(ndx))));
            }
        }
        
        public int GetInCount() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetInCount19)));
            }
        }
        
        public int GetInDataSize() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetInDataSize20)));
            }
        }
        
        public byte[] GetInData(int ndx) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cbyte(@__env, @__env.CallObjectMethodPtr(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetInData21, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(ndx)));
            }
        }
        
        public int ReadSignalStrength() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_ReadSignalStrength22)));
            }
        }
        
        public void WritePacket(byte[] pkt) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_WritePacket23, global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, pkt));
            }
        }
        
        public int GetSentState() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_GetSentState24)));
            }
        }
        
        public void SetSentState(int state) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_SetSentState25, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(state));
            }
        }
        
        public void UpdateConnection(int interval_min, int interval_max, int latency, int timeout) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 18)){
            @__env.CallVoidMethod(this, global::RMIRWin10BLE.@__IBleInterface.j4n_UpdateConnection26, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(interval_min), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(interval_max), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(latency), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(timeout));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__IBleInterface);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ConnectBLE", "ConnectBLE0", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DisconnectBLE", "DisconnectBLE1", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DiscoverUEI", "DiscoverUEI2", "(Z)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ConnectUEI", "ConnectUEI3", "(Ljava/lang/String;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DisconnectUEI", "DisconnectUEI4", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "DiscoverServices", "DiscoverServices5", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetFeatures", "GetFeatures6", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetSubscription", "GetSubscription7", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetStage", "GetStage8", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetDisconnecting", "SetDisconnecting9", "(Z)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IsDisconnecting", "IsDisconnecting10", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IsScanning", "IsScanning11", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IsConnected", "IsConnected12", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "HasCCCD", "HasCCCD13", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "NeedsCCCD", "NeedsCCCD14", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetListSize", "GetListSize15", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetListItem", "GetListItem16", "(I)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetItemName", "GetItemName17", "(I)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRssi", "GetRssi18", "(I)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetInCount", "GetInCount19", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetInDataSize", "GetInDataSize20", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetInData", "GetInData21", "(I)[B"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReadSignalStrength", "ReadSignalStrength22", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "WritePacket", "WritePacket23", "([B)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetSentState", "GetSentState24", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetSentState", "SetSentState25", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "UpdateConnection", "UpdateConnection26", "(IIII)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ConnectBLE0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle portName) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.ConnectBLE(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, portName)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void DisconnectBLE1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__real.DisconnectBLE();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void DiscoverUEI2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, bool start) {
            // (Z)V
            // (Z)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__real.DiscoverUEI(start);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool ConnectUEI3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle address) {
            // (Ljava/lang/String;)Z
            // (LSystem/String;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.ConnectUEI(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, address))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle DisconnectUEI4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.DisconnectUEI());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool DiscoverServices5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.DiscoverServices()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool GetFeatures6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.GetFeatures()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetSubscription7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.GetSubscription());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int GetStage8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((int)(@__real.GetStage()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void SetDisconnecting9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, bool disconnecting) {
            // (Z)V
            // (Z)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__real.SetDisconnecting(disconnecting);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool IsDisconnecting10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.IsDisconnecting()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsScanning11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.IsScanning()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsConnected12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.IsConnected()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool HasCCCD13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.HasCCCD()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool NeedsCCCD14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((bool)(@__real.NeedsCCCD()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int GetListSize15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((int)(@__real.GetListSize()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetListItem16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int ndx) {
            // (I)Ljava/lang/String;
            // (I)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.GetListItem(ndx));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetItemName17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int ndx) {
            // (I)Ljava/lang/String;
            // (I)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.GetItemName(ndx));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int GetRssi18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int ndx) {
            // (I)I
            // (I)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((int)(@__real.GetRssi(ndx)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int GetInCount19(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((int)(@__real.GetInCount()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int GetInDataSize20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((int)(@__real.GetInDataSize()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetInData21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int ndx) {
            // (I)[B
            // (I)[B
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.GetInData(ndx));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int ReadSignalStrength22(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((int)(@__real.ReadSignalStrength()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void WritePacket23(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle pkt) {
            // ([B)V
            // ([B)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__real.WritePacket(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cbyte(@__env, pkt));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int GetSentState24(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__return = ((int)(@__real.GetSentState()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void SetSentState25(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int state) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__real.SetSentState(state);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void UpdateConnection26(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int interval_min, int interval_max, int latency, int timeout) {
            // (IIII)V
            // (IIII)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::RMIRWin10BLE.IBleInterface @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::RMIRWin10BLE.IBleInterface>(@__env, @__obj);
            @__real.UpdateConnection(interval_min, interval_max, latency, timeout);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::RMIRWin10BLE.@__IBleInterface(@__env);
            }
        }
    }
    #endregion
}
