// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package rmirwin10ble;

@net.sf.jni4net.attributes.ClrInterface
public interface IBleInterface {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    java.lang.String ConnectBLE(java.lang.String portName);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void DisconnectBLE();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    void DiscoverUEI(boolean start);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Z")
    boolean ConnectUEI(java.lang.String address);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    java.lang.String DisconnectUEI();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean DiscoverServices();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean GetFeatures();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    java.lang.String GetSubscription();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    int GetStage();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    void SetDisconnecting(boolean disconnecting);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean IsDisconnecting();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean IsScanning();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean IsConnected();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean HasCCCD();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    boolean NeedsCCCD();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    int GetListSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/String;")
    java.lang.String GetListItem(int ndx);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/String;")
    java.lang.String GetItemName(int ndx);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)I")
    int GetRssi(int ndx);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    int GetInCount();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    int GetInDataSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)[B")
    byte[] GetInData(int ndx);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    int ReadSignalStrength();
    
    @net.sf.jni4net.attributes.ClrMethod("([B)V")
    void WritePacket(byte[] pkt);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    int GetSentState();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    void SetSentState(int state);
    
    @net.sf.jni4net.attributes.ClrMethod("(IIII)V")
    void UpdateConnection(int interval_min, int interval_max, int latency, int timeout);
    //</generated-interface>
}
